#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-worker-sample"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
