name: JS SDK CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check-ts-compat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ts-version: [
          {display: "v4.0.2", tag: "", tsc_args: ""},
          {display: "v5.x", tag: "<6.0.0", tsc_args: ""},
          {display: "v6.x", tag: "<7.0.0", tsc_args: "--ignoreDeprecations 6.0"},
        ]
    name: TypeScript ${{ matrix.ts-version.display }} compatibility check
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install dependencies & build
        run: npm install

      - name: Set TypeScript version
        if: matrix.ts-version.tag != ''
        working-directory: ./extra-checks/ts-compat-check
        run: npm install typescript@"${{ matrix.ts-version.tag }}"

      - name: Run check
        working-directory: ./extra-checks/ts-compat-check
        run: npm run check -- ${{ matrix.ts-version.tsc_args }}

  test-browser-chrome:
    # Runner image version is temporarily pinned to `ubuntu-22.04`.
    # TODO: Restore it to `ubuntu-latest` as soon as compatibility issues with `browser-actions/setup-chrome@latest` are sorted out.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chrome: ["beta", "stable"]
    name: Browser - Chrome ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Setup chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: CHROME_BIN=$(which chrome) npm run test:browser:chrome

  test-browser-chromium:
    runs-on: windows-latest
    strategy:
      matrix:
        chrome: ["592002", "612439", "722274"]
    name: Browser - Chromium ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Setup chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: |
          $env:CHROMIUM_BIN='${{ steps.setup-chrome.outputs.chrome-path }}'; npm run test:browser:chromium

  test-browser-firefox:
    # Runner image version is temporarily pinned to `ubuntu-22.04`.
    # TODO: Restore it to `ubuntu-latest` as soon as compatibility issues with `browser-actions/setup-firefox@latest` are sorted out.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        firefox: ["84.0", "latest", "latest-beta"]
    name: Browser - Firefox ${{ matrix.firefox }} test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:browser:firefox

  test-browser-safari:
    runs-on: macos-latest
    name: Browser - Safari latest test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Enable Safari automation
        run: |
          sudo safaridriver --enable
          /Applications/Safari.app/Contents/MacOS/Safari & sleep 5
          killall Safari

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:browser:safari

  test-bun:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bun-version: ["1.1.0", "latest"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Bun ${{ matrix.bun-version }} (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v7

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:bun

  test-chromium-extension-chrome:
    # Runner image version is temporarily pinned to `ubuntu-22.04`.
    # TODO: Restore it to `ubuntu-latest` as soon as compatibility issues with `browser-actions/setup-chrome@latest` are sorted out.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chrome: ["beta", "stable"]
    name: Chromium Extension - Chrome ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Setup chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: CHROME_BIN=$(which chrome) npm run test:chromium-extension:chrome

  test-chromium-extension-chromium:
    runs-on: windows-latest
    strategy:
      matrix:
        chrome: ["612439", "722274"]
    name: Chromium Extension - Chromium ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Setup chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: |
          $env:CHROMIUM_BIN='${{ steps.setup-chrome.outputs.chrome-path }}'; npm run test:chromium-extension:chromium

  test-cloudflare-worker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Cloudflare Worker (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:cloudflare-worker

  test-deno:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno-version: [~1.46, vx.x.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Deno ${{ matrix.deno-version }} (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v7

      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:deno

  test-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x, 24.x, 26.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Node.js ${{ matrix.node-version }} (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Apply workaround for yargs issue on Node 26+
        if: matrix.node-version == '26.x'
        # see also: https://github.com/yargs/yargs/issues/2509#issuecomment-4412569569
        run: npm pkg set overrides.mocha.yargs=^18.0.0

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:node

  coverage:
    needs: [
      check-ts-compat,
      test-browser-chrome, test-browser-chromium, test-browser-firefox, ## test-browser-safari,
      test-bun,
      test-chromium-extension-chrome, test-chromium-extension-chromium,
      test-cloudflare-worker,
      test-deno,
      test-node
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run coverage

      - name: Upload coverage folder
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: coverage
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC (see also https://docs.npmjs.com/trusted-publishers)
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies & build
        run: npm install

      - name: 🚀Publish
        run: npm publish --access public
