name: JS SDK CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check-ts-compat:
    runs-on: ubuntu-latest
    name: TypeScript v4.0.2 compatibility check
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies & build
        run: npm install

      - name: Run check
        run: npm run check:ts-compat

  test-browser-chrome:
    # Runner image version is temporarily pinned to `ubuntu-22.04`.
    # TODO: Restore it to `ubuntu-latest` as soon as compatibility issues with `browser-actions/setup-chrome@latest` are sorted out.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chrome: ["beta", "stable"]
    name: Browser - Chrome ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: CHROME_BIN=$(which chrome) npm run test:browser:chrome

  test-browser-chromium:
    runs-on: windows-latest
    strategy:
      matrix:
        chrome: ["592002", "612439", "722274"]
    name: Browser - Chromium ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: |
          $env:CHROMIUM_BIN='${{ steps.setup-chrome.outputs.chrome-path }}'; npm run test:browser:chromium

  test-browser-firefox:
    # Runner image version is temporarily pinned to `ubuntu-22.04`.
    # TODO: Restore it to `ubuntu-latest` as soon as compatibility issues with `browser-actions/setup-firefox@latest` are sorted out.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        firefox: ["84.0", "latest", "latest-beta"]
    name: Browser - Firefox ${{ matrix.firefox }} test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:browser:firefox

  test-browser-safari:
    runs-on: macos-latest
    name: Browser - Safari latest test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Safari automation
        run: |
          sudo safaridriver --enable
          /Applications/Safari.app/Contents/MacOS/Safari & sleep 5
          killall Safari

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:browser:safari

  test-bun:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        bun-version: ["1.1.0", "latest"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    name: Bun ${{ matrix.bun-version }} (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:bun

  test-chromium-extension-chrome:
    # Runner image version is temporarily pinned to `ubuntu-22.04`.
    # TODO: Restore it to `ubuntu-latest` as soon as compatibility issues with `browser-actions/setup-chrome@latest` are sorted out.
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chrome: ["beta", "stable"]
    name: Chromium Extension - Chrome ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: CHROME_BIN=$(which chrome) npm run test:chromium-extension:chrome

  test-chromium-extension-chromium:
    runs-on: windows-latest
    strategy:
      matrix:
        chrome: ["612439", "722274"]
    name: Chromium Extension - Chromium ${{ matrix.chrome }} test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: |
          $env:CHROMIUM_BIN='${{ steps.setup-chrome.outputs.chrome-path }}'; npm run test:chromium-extension:chromium

  test-cloudflare-worker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Cloudflare Worker (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:cloudflare-worker

  test-deno:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno-version: [~1.31, ~1.46, vx.x.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # Test run on Deno 1.31/Windows is slow as hell. (It seems to involve a lot of setup,
        # Deno downloads half the NPM...). We can live without these tests.
        exclude:
          - deno-version: ~1.31
            os: windows-latest
    name: Deno ${{ matrix.deno-version }} (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:deno

  test-node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - node-version: 14.x
            os: macOS-latest
    name: Node.js ${{ matrix.node-version }} (${{ matrix.os }}) test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run test:node

  coverage:
    needs: [
      check-ts-compat,
      test-browser-chrome, test-browser-chromium, test-browser-firefox, test-browser-safari,
      test-bun,
      test-chromium-extension-chrome, test-chromium-extension-chromium,
      test-cloudflare-worker,
      test-deno,
      test-node
    ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run coverage

      - name: Upload coverage folder
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish:
    needs: coverage
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: 🚀Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_KEY }}
